#!/bin/sh
. /etc/default/hadoop

# Instead of bigtop-detect-javahome
. /etc/hive-hcatalog/conf/hcat-env.sh

# FIXME: HCATALOG-636 (and also HIVE-2757)
export HIVE_HOME=/usr/lib/hive
export HIVE_CONF_DIR=/etc/hive/conf
export HCAT_HOME=/usr/lib/hive-hcatalog

export HCATALOG_HOME=/usr/lib/hive-hcatalog
exec /usr/lib/hive-hcatalog/bin/hcat "$@"
