# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0.

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      java-patch-and-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
