package org.apache.ambari.server.fsm;

public enum NodeServiceComponentEventType {
  NODE_SVCCOMP_OP_IN_PROGRESS,
  NODE_SVCCOMP_OP_SUCCEEDED,
  NODE_SVCCOMP_OP_FAILED,
  NODE_SVCCOMP_OP_RESTART,
  NODE_SVCCOMP_INSTALL,
  NODE_SVCCOMP_START,
  NODE_SVCCOMP_STOP,
  NODE_SVCCOMP_UNINSTALL,
  NODE_SVCCOMP_WIPEOUT  
}
