#!/usr/bin/env bash
# Copyright 2011 The Apache Software Foundation
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

python_is_supported() {
  command -v "$1" >/dev/null 2>&1 \
    && "$1" -c "import sys; sys.exit(sys.version_info < (3, 9, 2))" >/dev/null 2>&1
}

if [ -n "${PYTHON:-}" ] && ! python_is_supported "$PYTHON"; then
  PYTHON=""
fi

if [ -z "${PYTHON:-}" ] && python_is_supported /usr/bin/python3.9; then
  PYTHON=/usr/bin/python3.9
fi

if [ -z "${PYTHON:-}" ] && python_is_supported /usr/bin/python3; then
  PYTHON=/usr/bin/python3
fi

if [ -z "${PYTHON:-}" ]; then
  echo "Cannot detect Python 3.9.2 or newer for Ambari." >&2
  exit 1
fi

exec "$PYTHON" "$@"
