/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const ServiceComponentMetricsEnums = {
  HDFS: {
    metrics: {
      CapacityTotal: "capacityTotal",
      CapacityUsed: "capacityUsed",
      CapacityRemaining: "capacityRemaining",
      CapacityNonDFSUsed: "capacityNonDfsUsed",
      BlocksTotal: "dfsTotalBlocksValues",
      CorruptBlocks: "dfsCorruptBlocksValues",
      MissingBlocks: "dfsMissingBlocksValues",
      UnderReplicatedBlocks: "dfsUnderReplicatedBlocksValues",
      FilesTotal: "dfsTotalFilesValues",
      UpgradeFinalized: "upgradeFinalized", //to be changed
      HeapMemoryUsed: "jvmMemoryHeapUsedValues",
      HeapMemoryMax: "jvmMemoryHeapMaxValues",
      StartTime: "namenodeUptime",
      Safemode: "safeModeStatus",
      LiveNodes: "liveNodesDataNodes",
      DeadNodes: "deadNodesDataNodes",
      DecomNodes: "decommissionedNodesDataNodes",
    },
    dataNodesStarted: "dataNodesStarted",
    dataNodesInstalled: "dataNodesInstalled",
    dataNodesTotal: "dataNodesTotal",
    routersStarted: "routersStarted",
    routersInstalled: "routersInstalled",
    routersTotal: "routersTotal",
    nfsGatewaysStarted: "nfsGatewaysStarted",
    nfsGatewaysInstalled: "nfsGatewaysInstalled",
    nfsGatewaysTotal: "nfsGatewaysTotal",
    journalNodes: "journalNodes",
    nameNode: "nameNode",
    snameNode: "snameNode",
    activeNameNodes: "activeNameNodes",
    standbyNameNodes: "standbyNameNodes",
    nonActiveStandbyNamenodes: "nonActiveStandbyNamenodes",
    isNameNodeHaEnabled: "isNameNodeHaEnabled",
    datanodes: "datanodes",
    zookeeperFailoverControllers: "zookeeperFailoverControllers",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    clientComponents: "clientComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  YARN: {
    metrics: {
      yarn: {
        Queue: {
          root: {
            AppsSubmitted: "appsSubmitted",
            AppsRunning: "appsRunning",
            AppsPending: "appsPending",
            AppsCompleted: "appsCompleted",
            AppsKilled: "appsKilled",
            AppsFailed: "appsFailed",
            AllocatedContainers: "containersAllocated",
            PendingContainers: "containersPending",
            ReservedContainers: "containersReserved",
            ReservedMB: "reservedMemory",
            AvailableMB: "availableMemory",
            UsedAMResourceMB: "usedMemory",
          },
        },
        clusterMetrics: {
          NumActiveNMs: "nodeManagersCountActive",
          NumLostNMs: "nodeManagersCountLost",
          NumUnhealthyNMs: "nodeManagersCountUnhealthy",
          NumRebootedNMs: "nodeManagersCountRebooted",
          NumDecommissionedNMs: "nodeManagersCountDecommissioned",
        },
      },
      jvm: {
        HeapMemoryUsed: "jvmMemoryHeapUsed",
        HeapMemoryMax: "jvmMemoryHeapMax",
      },
      runTime: {
        StartTime: "resourceManagerUptime",
      },
    },
    resourceManager: "resourceManager",
    activeResourceManagers: "activeResourceManagers",
    standbyResourceManagers: "standbyResourceManagers",
    nonActiveStandbyResourceManagers: "nonActiveStandbyResourceManagers",
    nodeManagersStarted: "nodeManagersStarted",
    nodeManagersInstalled: "nodeManagersInstalled",
    nodeManagersTotal: "nodeManagersTotal",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    clientComponents: "clientComponents",
    yarnClients: "yarnClients",
    isRMHAEnabled: "isRMHAEnabled",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  ZOOKEEPER: {
    masterComponents: "masterComponents",
    clientComponents: "clientComponents",
    zookeeperClientData: "zookeeperClientData",
    zkClientsInstalled: "zkClientsInstalled",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  HBASE: {
    metrics: {
      MasterStartTime: "masterStartTime",
      MasterActiveTime: "masterActiveTime",
      AverageLoad: "averageLoad",
      ritCount: "regionsInTransition",
      HeapMemoryUsed: "heapMemoryUsed",
      HeapMemoryMax: "heapMemoryMax",
    },
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    clientComponents: "clientComponents",
    activeHbaseMasters: "activeHbaseMasters",
    standbyHbaseMasters: "standbyHbaseMasters",
    nonActiveStandbyHbaseMasters: "nonActiveStandbyHbaseMasters",
    hbaseRegionServersStarted: "hbaseRegionServersStarted",
    hbaseRegionServersInstalled: "hbaseRegionServersInstalled",
    hbaseRegionServersTotal: "hbaseRegionServersTotal",
    phoenixServersStarted: "phoenixServersStarted",
    phoenixServersInstalled: "phoenixServersInstalled",
    phoenixServersTotal: "phoenixServersTotal",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  RANGER: {
    metrics: {
      rangerTagSyncsStarted: "rangerTagSyncsStarted",
      rangerTagSyncsInstalled: "rangerTagSyncsInstalled",
      rangerTagSyncsTotal: "rangerTagSyncsTotal",
    },
    pluginProperties: {
      "ranger-hdfs-plugin-properties": "rangerHDFSPluginProperties",
      "ranger-hbase-plugin-properties": "rangerHbasePluginProperties",
      "hive-env": "rangerHivePluginProperties",
      "ranger-yarn-plugin-properties": "rangerYarnPluginProperties",
    },
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    rangerAdmins: "rangerAdmins",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  MAPREDUCE2: {
    jobHistoryServer: "jobHistoryServer",
    masterComponents: "masterComponents",
    clientComponents: "clientComponents",
    mapReduce2Clients: "mapReduce2Clients",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  TEZ: {
    tezClientsStarted: "tezClientsStarted",
    tezClientsInstalled: "tezClientsInstalled",
    tezClientsTotal: "tezClientsTotal",
    slaveComponents: "slaveComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  SPARK3: {
    spark3JobHistoryServers: "spark3JobHistoryServers",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    clientComponents: "clientComponents",
    spark3Clients: "spark3Clients",
    livyForSpark3ServerInstalledCount: "livyForSpark3ServerInstalledCount",
    livyForSpark3ServerStartedCount: "livyForSpark3ServerStartedCount",
    livyForSpark3ServerTotalCount: "livyForSpark3ServerTotalCount",
    spark3ThriftServerInstalledCount: "spark3ThriftServerInstalledCount",
    spark3ThriftServerStartedCount: "spark3ThriftServerStartedCount",
    spark3ThriftServerTotalCount: "spark3ThriftServerTotalCount",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  KERBEROS: {
    clientComponents: "clientComponents",
    kerberosClientsInstalled: "kerberosClientsInstalled",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  RANGER_KMS: {
    masterComponents: "masterComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  AMBARI_METRICS: {
    grafana: "grafana",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    metricsMonitorsStartedCount: "metricsMonitorsStartedCount",
    metricsMonitorsInstalledCount: "metricsMonitorsInstalledCount",
    metricsMonitorsTotalCount: "metricsMonitorsTotalCount",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  HIVE: {
    masterComponents: "masterComponents",
    clientComponents: "clientComponents",
    hiveClients: "hiveClients",
    alertsCount: "alertsCount",
    state: "serviceState",
    hiveServer2JDBCURL: "hiveServer2JDBCURL",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  TRINO: {
    trinoCoordinators: "trinoCoordinators",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    clientComponents: "clientComponents",
    trinoClients: "trinoClients",
    trinoWorkerInstalledCount: "trinoWorkerInstalledCount",
    trinoWorkerStartedCount: "trinoWorkerStartedCount",
    trinoWorkerTotalCount: "trinoWorkerTotalCount",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  SSM: {
    smartAgentsStartedCount: "smartAgentsStartedCount",
    smartAgentsInstalledCount: "smartAgentsInstalledCount",
    smartAgentsTotalCount: "smartAgentsTotalCount",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    smartServers: "smartServers",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  SQOOP: {
    sqoopClientsStarted: "sqoopClientsStarted",
    sqoopClientsInstalled: "sqoopClientsInstalled",
    sqoopClientsTotal: "sqoopClientsTotal",
    clientComponents: "clientComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  KYUUBI: {
    masterComponents: "masterComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
  },
  TRINO_GATEWAY: {
    trinoGateway: "trinoGateway",
    masterComponents: "masterComponents",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
    isRestartRequiredForService: "isRestartRequiredForService",
    isInPassiveForService: "isInPassiveForService",
  },
  PINOT: {
    pinotController: "pinotController",
    pinotBroker: "pinotBroker",
    pinotMinion: "pinotMinion",
    pinotServer: "pinotServer",
    masterComponents: "masterComponents",
    slaveComponents: "slaveComponents",
    pinotBrokerStartedCount: "pinotBrokerStartedCount",
    pinotBrokerInstalledCount: "pinotBrokerInstalledCount",
    pinotBrokerTotalCount: "pinotBrokerTotalCount",
    pinotMinionStartedCount: "pinotMinionStartedCount",
    pinotMinionInstalledCount: "pinotMinionInstalledCount",
    pinotMinionTotalCount: "pinotMinionTotalCount",
    pinotServerStartedCount: "pinotServerStartedCount",
    pinotServerInstalledCount: "pinotServerInstalledCount",
    pinotServerTotalCount: "pinotServerTotalCount",
    alertsCount: "alertsCount",
    state: "serviceState",
    hasCriticalAlerts: "hasCriticalAlerts",
    isRestartRequiredForService: "isRestartRequiredForService",
    isInPassiveForService: "isInPassiveForService",
  },
};
