#!/usr/bin/env bash
# chkconfig: 345 20 80
# description: ambari-server daemon
# processname: ambari-server

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME=ambari-server
PIDFILE=/var/run/$NAME/$NAME.pid

case "$1" in
  start)
        /usr/sbin/ambari-server $@
        ;;
  stop)
        /usr/sbin/ambari-server $@
        ;;
  status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
          PID=`cat $PIDFILE`
           if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
             printf "%s\n" "Process dead but pidfile exists"
             exit 1
           else
            echo "Running"
            exit 0
          fi
        else
          printf "%s\n" "Service not running"
          exit 1
        fi
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 0
