/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ambari.server.controller.dependencies;

public enum ManagedDependencyErrorCode {
  INVALID_BINDING_ID,
  INVALID_CONSUMER_DESCRIPTOR,
  INVALID_PROVIDER_DESCRIPTOR,
  DEPENDENCY_LOCAL_DATA_MIGRATION_UNSUPPORTED,
  DEPENDENCY_VERSION_UNSUPPORTED,
  DEPENDENCY_CLIENT_FEATURE_UNSUPPORTED,
  DEPENDENCY_PROVIDER_NOT_READY,
  DEPENDENCY_SECURITY_MISMATCH,
  CROSS_REALM_NOT_SUPPORTED,
  SAME_REALM_BINDING_NOT_AVAILABLE,
  DEPENDENCY_SECURITY_PROOF_MISSING,
  DEPENDENCY_SECURITY_PROOF_UPDATE_REQUIRED,
  DEPENDENCY_HDFS_AUTH_TO_LOCAL_UNMANAGED,
  DEPENDENCY_HDFS_AUTH_TO_LOCAL_UNSUPPORTED,
  DEPENDENCY_HDFS_AUTH_TO_LOCAL_MISMATCH,
  DEPENDENCY_HDFS_AUTH_TO_LOCAL_STALE,
  DEPENDENCY_KRB5_DEFAULT_REALM_UNPROVEN,
  DEPENDENCY_ZOOKEEPER_AUTHORIZATION_STALE,
  DEPENDENCY_AUTHORIZATION_FAILED,
  DEPENDENCY_NAMESPACE_CONFLICT,
  DEPENDENCY_NAMENODE_INVALID,
  DEPENDENCY_ZOOKEEPER_INVALID,
  DEPENDENCY_SNAPSHOT_NOT_APPROVED,
  DEPENDENCY_CONSUMER_NOT_READY,
  DEPENDENCY_OPERATION_STALE,
  DEPENDENCY_FENCING_UNCERTAIN,
  DEPENDENCY_PROVIDER_ACTION_FAILED,
  DEPENDENCY_CLIENT_PACKAGE_MISMATCH,
  DEPENDENCY_CLIENT_CONFIG_MISMATCH,
  DEPENDENCY_CLIENT_IDENTITY_MISMATCH,
  DEPENDENCY_NAMENODE_RPC_FAILED,
  DEPENDENCY_DATANODE_READ_WRITE_FAILED,
  DEPENDENCY_DATA_INTEGRITY_FAILED,
  DEPENDENCY_PROBE_CLEANUP_FAILED,
  DEPENDENCY_ZOOKEEPER_SESSION_FAILED,
  DEPENDENCY_ZOOKEEPER_AUTHORIZATION_FAILED,
  DEPENDENCY_ZOOKEEPER_HANDOFF_RECONCILIATION_REQUIRED,
  DEPENDENCY_COMMAND_INVALID
}
