# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
version: '3.3'
services:
  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION:-3.4.10}
    restart: always
    hostname: zookeeper
    networks:
      - infra-network
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
  solr:
    image: ambari-infra-solr:v1.0
    restart: always
    hostname: solr
    ports:
      - "8983:8983"
      - "5005:5005"
    networks:
      - infra-network
    env_file:
      - Profile
    entrypoint:
      - solr
      - start
      - "-f"
      - "-force"
      - "-c"
      - "-z"
      - ${ZOOKEEPER_CONNECTION_STRING}
    volumes:
      - $AMBARI_LOCATION/ambari-logsearch/ambari-logsearch-server/src/main/configsets:/usr/lib/ambari-infra-solr/server/solr/configsets
    extra_hosts:
      - metrics_collector:$DOCKERIP
networks:
  infra-network:
    driver: bridge

