//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 04:53:46 PM PDT 
//


package org.apache.ambari.common.rest.entities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NodeType complex type.
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType", propOrder = {
    "name",
    "nodeAttributes",
    "nodeState",
    "agentDeploymentState"
})
public class Node {
    
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "NodeAttributes", required = true)
    protected NodeAttributes nodeAttributes;
    @XmlElement(name = "NodeState", required = true)
    protected NodeState nodeState;
   
	public Node () {}

	public Node (String name) {
		this.name = name;
	}
	
	/*
	 * 
	 */
	public void releaseNodeFromCluster() {
		this.nodeState.setClusterName(null);
		this.getNodeState().setNodeServers(null);
	}
	
	/*
	 * Reserving node for cluster is done by associating cluster name w/ node
	 */
	public void reserveNodeForCluster (String clusterName, Boolean agentInstalled) {
		this.getNodeState().setClusterName(clusterName);
		this.getNodeState().setAgentInstalled(agentInstalled);
	}
	
	/*
	 * 
	 */
	public List<String> getAssociatedRoleNames() throws Exception {
		List<String> list = new ArrayList<String>();
		if (this.getNodeState().getClusterName() != null) {
			for (RoleToNodesMapEntry rnme : Clusters.getInstance().getCluster(this.getNodeState().getClusterName()).getRoleToNodesMap().getRoleToNodesMapEntry()) {
				list.add(rnme.getRoleName());
			}
		}
		return list;
	}
	
    /**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	/**
	 * @return the nodeMetrics
	 */
	public NodeAttributes getNodeAttributes() {
		return nodeAttributes;
	}
	/**
	 * @param nodeMetrics the nodeMetrics to set
	 */
	public void setNodeAttributes(NodeAttributes nodeAttributes) {
		this.nodeAttributes = nodeAttributes;
	}
	/**
	 * @return the nodeState
	 */
	public NodeState getNodeState() {
		return nodeState;
	}
	
	/**
	 * @param nodeState the nodeState to set
	 */
	public void setNodeState(NodeState nodeState) {
		this.nodeState = nodeState;
	}
}
