//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 04:53:46 PM PDT 
//


package org.apache.ambari.common.rest.entities;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

import javax.ws.rs.DefaultValue;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


public class Nodes {
	
	public static final String AGENT_DEPLOYMENT_STATE_TOBE_INSTALLED = "AGENT_TOBE_INSTALLED";
	public static final String AGENT_DEPLOYMENT_STATE_INSTALLED = "AGENT_INSTALLED";
	
	
	public static final short NODE_HEARTBEAT_INTERVAL_IN_MINUTES = 5;
	public static final short NODE_MAX_MISSING_HEARBEAT_INTERVALS = 3;
	
	// One node name to Node hashmap
	protected ConcurrentHashMap<String, Node> nodes = new ConcurrentHashMap<String, Node>();
	
	// Cluster name to Node names hash map
	protected ConcurrentHashMap<String, ConcurrentHashMap<String, String>> cluster_to_nodes = new ConcurrentHashMap<String, ConcurrentHashMap<String, String>>();
	
	/**
	 * @return the cluster_to_nodes
	 */
	public ConcurrentHashMap<String, ConcurrentHashMap<String, String>> getCluster_to_nodes() {
		return cluster_to_nodes;
	}

	private static Nodes NodesTypeRef=null;
	
	private Nodes() {}
	    
	public static synchronized Nodes getInstance() {
		if(NodesTypeRef == null) {
			NodesTypeRef = new Nodes();
		}
	    return NodesTypeRef;
	}

	public Object clone() throws CloneNotSupportedException {
		throw new CloneNotSupportedException();
	}
	   
	public ConcurrentHashMap<String, Node> getNodes () {
		return nodes;
	}
	
	public List<Node> getNodes (String clusterName, String roleName) {
		
		return null;
	}
}
