//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 04:53:46 PM PDT 
//


package org.apache.ambari.common.rest.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeServer", propOrder = {
    "name",
	"state",
	"lastStateUpdateTime"
})
public class NodeServer {

	public static final String NODE_SERVER_STATE_UP = "UP";
	public static final String NODE_SERVER_STATE_DOWN = "DOWN";
	
	/*
	 * name should be component/service name : role name
	 */
	@XmlElement(name = "Name", required = true)
	protected String name;
	
	@XmlElement(name = "State", required = true)
	protected String state;  // UP/DOWN
	
	@XmlElement(name = "LastStateUpdateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastStateUpdateTime;
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}


	/**
	 * @return the lastStateUpdateTime
	 */
	public XMLGregorianCalendar getLastStateUpdateTime() {
		return lastStateUpdateTime;
	}

	/**
	 * @param lastStateUpdateTime the lastStateUpdateTime to set
	 */
	public void setLastStateUpdateTime(XMLGregorianCalendar lastStateUpdateTime) {
		this.lastStateUpdateTime = lastStateUpdateTime;
	}

	/**
	 * @param creationTime the creationTime to set
	 */
	protected void setLastUpdateTime(Date lastStateUpdateTime) throws Exception {
		GregorianCalendar cal = new GregorianCalendar();
		cal.setTime(lastStateUpdateTime);
		this.lastStateUpdateTime = DatatypeFactory.newInstance().newXMLGregorianCalendar(cal);
	}

}
