//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 04:53:46 PM PDT 
//


package org.apache.ambari.common.rest.entities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleToNodesMapEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoleToNodesMapEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RoleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NodeRangeExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleToNodesMapEntry", propOrder = {
    "roleName",
    "nodeRangeExpressions"
})
public class RoleToNodesMapEntry {

    @XmlElement(name = "RoleName", required = true)
    protected String roleName;
    @XmlElement(name = "Nodes", required = true)
    protected List<String> nodeRangeExpressions;
    
	/**
	 * @return the roleName
	 */
	public String getRoleName() {
		return roleName;
	}
	/**
	 * @param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	/**
	 * @return the nodeRangeExpressions
	 */
	public List<String> getNodeRangeExpressions() {
		return nodeRangeExpressions;
	}
	/**
	 * @param nodeRangeExpressions the nodeRangeExpressions to set
	 */
	public void setNodeRangeExpressions(List<String> nodeRangeExpressions) {
		this.nodeRangeExpressions = nodeRangeExpressions;
	}
}
