name: ambari-web-tester

on: [push]

jobs:
  ambari-web-test:
    runs-on: ubuntu-latest
    env:
      npm_config_tmp: /tmp/npm_config_tmp
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '4.5.0'
      - run: npm install -g yarn@0.23.2
      - run: yarn install --ignore-engines --pure-lockfile
        working-directory: ./ambari-web
      - run: yarn test
        working-directory: ./ambari-web
